### ISSUE TITLE
stc15 pcf8591同时采集两个模拟，

### ISSUE THREAD

**Issue by yueyuan123** [DT9025A/lanqiao#1]
pcf8591同时采集两个模拟，数据是被调换过的
这是为什么呢？

**Comment by DT9025A** [comment]
方便的话可以提供一下代码吗|∀ﾟ

**Comment by yueyuan123** [comment]
#include ”ds1302.h”删了吧，没用上，你试试，那两个zuzhi和liangdu的值是相反的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DT9025A/lanqiao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DT9025A/lanqiao] stc15 pcf8591同时采集两个模拟， (Issue #1)





 
方便的话可以提供一下代码吗|∀ﾟ

**Comment by DT9025A** [comment]
> #include ”ds1302.h”删了吧，没用上，你试试，那两个zuzhi和liangdu的值是相反的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DT9025A/lanqiao" ***@***.***&gt;; 发送时间:&nbsp;2022年3月29日(星期二) 中午11:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [DT9025A/lanqiao] stc15 pcf8591同时采集两个模拟， (Issue #1) 方便的话可以提供一下代码吗|∀ﾟ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

并没有找到代码哦，要不试一下直接发到邮箱里面怎么样呢

**Comment by yueyuan123** [comment]
额，咱俩加一下QQ？319244199我的QQ号，你备注一下

**Comment by yueyuan123** [comment]
unsigned char iic_use(unsigned char add)
{
	unsigned char temp;
	IIC_Start();
	IIC_SendByte(0x90);
	IIC_WaitAck();
	IIC_SendByte(add);
	IIC_WaitAck();
	IIC_Stop();
	
	IIC_Start();
	IIC_SendByte(0x91);
	IIC_WaitAck();
	temp=IIC_RecByte();
	IIC_Stop();
	
	return temp;
}
while(1)
	{
		zuzhi=iic_use(0x03)*0.392;
		liangdu=iic_use(0x01)*0.392;
		wendu=ds18b20_read();
		//xwendu=xs_ds18b20_read();
		yi=20;er=liangdu/100;san=liangdu%100/10;si=liangdu%10;wu=zuzhi%100/10;liu=zuzhi%10;qi=wendu%100/10;ba=wendu%10;
		display1(yi,er,san,si);
		display2(wu,liu,qi,ba);


上面是初始化的函数，下面是在主函数里用的函数

**Comment by DT9025A** [comment]
详细的分析在PDF内附上，希望对你有帮助
[report.pdf](https://github.com/DT9025A/lanqiao/files/8385661/report.pdf)

**Comment by yueyuan123** [comment]
也就是说实际上只进行一个通道读取的时候，也是在第二次的时候才被传输的

**Comment by DT9025A** [comment]
是的，第一次读取的数值恒为80H

**Comment by yueyuan123** [comment]
OK，谢谢啦
