### ISSUE TITLE
关于ds1302数据的问题

### ISSUE THREAD

**Issue by yueyuan123** [DT9025A/lanqiao#2]
老哥儿，还有问题哦
unsigned char Read_Ds1302_Byte ( unsigned char address )
{
 	unsigned char i,temp=0x00,dat1,dat2;
 	RST=0;	_nop_();
 	SCK=0;	_nop_();
 	RST=1;	_nop_();
 	Write_Ds1302(address);
 	for (i=0;i<8;i++) 	
 	{		
		SCK=0;
		temp>>=1;	
 		if(SDA)
 		temp|=0x80;	
 		SCK=1;
	} 
	RST=0;	_nop_();
 	RST=0;	_nop_();
 	SCK=0;	_nop_();
	SCK=1;	_nop_();
	SDA=0;	_nop_();
	SDA=1;	_nop_();
	return (temp);			
}
这是蓝桥杯给的ds1302的驱动，为什么这一步中temp是10进制的（因为给芯片传入的就是十六进制，不知道为啥到这一步突然变成10进制了）写的时候数据一直有问题，研究半天发现这一步的时候数据已经被处理为10进制了，但是我不知道为什么。

**Comment by DT9025A** [comment]
没有处理哦，DS1302采用的是BCD码进行数据存储，驱动中并没有对其进行进制的转换，只是将数据原封不动的发送和接收，最后的数据处理还是要自己做的。

例如第八届省赛中：
```
Write_Ds1302_Byte (0x8e, 0x00);
Write_Ds1302_Byte (0x80, 0x50);
Write_Ds1302_Byte (0x82, 0x59);
Write_Ds1302_Byte (0x84, 0x23);
Write_Ds1302_Byte (0x8e, 0x80);
```
对寄存器0x8e的写入是为了关闭写保护，0x80，0x82，0x84分别对应秒，分钟，小时，数据是以BCD码的形式写入的。
```
h = Read_Ds1302_Byte (0x85);
Display_Buffer[0] = h / 16;
Display_Buffer[1] = h % 16;
```
对于读出数据的处理，分别提取出高四位与低四位即为所需的数值，也就是BCD码的编码规则，11(D)->0x11(BCD)。

**Comment by yueyuan123** [comment]
sbit SCK=P1^7;		
sbit SDA=P2^3;		
sbit RST = P1^3;   // DS1302复位												

void Write_Ds1302(unsigned  char temp) 
{
	unsigned char i;
	for (i=0;i<8;i++)     	
	{ 
		SCK=0;
		SDA=temp&0x01;
		temp>>=1; 
		SCK=1;
	}
}   

void Write_Ds1302_Byte( unsigned char address,unsigned char dat )     
{
 	RST=0;	_nop_();
 	SCK=0;	_nop_();
 	RST=1; 	_nop_();  
 	Write_Ds1302(address);	
 	Write_Ds1302(dat);		
 	RST=0; 
}

unsigned char Read_Ds1302_Byte ( unsigned char address )
{
 	unsigned char i,temp=0x00;
 	RST=0;	_nop_();
 	SCK=0;	_nop_();
 	RST=1;	_nop_();
 	Write_Ds1302(address);
 	for (i=0;i<8;i++) 	
 	{		
		SCK=0;
		temp>>=1;	
 		if(SDA)
 		temp|=0x80;	
 		SCK=1;
	} 
 	RST=0;	_nop_();
 	SCK=0;	_nop_();
	SCK=1;	_nop_();
	SDA=0;	_nop_();
	SDA=1;	_nop_();
	return (temp);			
}
那使用的时候驱动不变，在获取数据之后
void ds1302_start()
{
	uchar i;
	Write_Ds1302_Byte(0x8e,0x00);
	for(i=0;i<7;i++)
	{
		Write_Ds1302_Byte(write_ds[i],time[i]);
	}
	Write_Ds1302_Byte(0x8e,0x80);
}
void read_ds1302()
{
	uchar i;
	for(i=0;i<7;i++)
	{
		time[i]=Read_Ds1302_Byte(read_ds[i]);
	}
}
直接对time[]/16;和time[]%16;到这儿也没有什么问题
但是如果写time[]++；或者time[]--;之后，通过time[]/16;time%16;显示就有问题是为什么

**Comment by DT9025A** [comment]
看数据，比如0x09+1=0x0A就没办法正确显示了

**Comment by yueyuan123** [comment]
这是为什么呢

**Comment by DT9025A** [comment]
0x0A%16=10，如果你的段码表里面只有0-9的数据的话，是不是就会索引到不期望的数据了呢

**Comment by yueyuan123** [comment]
我知道为什么了，谢谢啦
